### ISSUE TITLE
Chart

### ISSUE THREAD

**Issue by rslruiz** [Meltartica/pl3ApolloProject#2]
Prepare a hierarchy chart [Gaddis. p.143].

**Comment by Meltartica** [comment]
I have uploaded our group's hierarchy chart. Thank you!

**Comment by rslruiz** [comment]
Remove the charts from README.md. Upload these as separate files.

**Comment by Meltartica** [comment]
Hi sir, I have now removed the charts from README.md and reuploaded them as separate files. Thank you!
